###
GET http://localhost/8080/contacts
###
GET http://localhost/8080/contacts/645396271394eecc72b83868
###
GET http://localhost/8080/contacts/645396271394eecc72b83869
###
GET http://localhost/8080/contacts/645396271394eecc72b8386a
###
GET https://week02.onrender.com/contacts
###
GET https://week02.onrender.com/contacts/645396271394eecc72b83868
###
GET https://week02.onrender.com/contacts/645396271394eecc72b83869
###
GET https://week02.onrender.com/contacts/645396271394eecc72b8386a
###
POST http://localhost/8080/contacts
content-type: application/json

{
	"firstName": "Erwin",
	"lastName": "Smith",
	"email": "erwinsmith@email.com",
	"favoriteColor": "gold",
	"birthday": "02/23/1988"
}
###
PUT http://localhost/8080/contacts/645396271394eecc72b83868
content-type: application/json

{
    "favoriteColor": "gray",
    "birthday": "11/11/2011"
}

DELETE http://localhost/8080/contacts/645396271394eecc72b83868

### RENDER
POST https://week03.onrender.com/contacts/
content-type: application/json

{
	"firstName": "Erwin",
	"lastName": "Smith",
	"email": "erwinsmith@email.com",
	"favoriteColor": "gold",
	"birthday": "02/23/1988"
}

###
PUT https://week03.onrender.com/contacts/645396271394eecc72b83868
content-type: application/json

{
    "favoriteColor": "gray",
    "birthday": "11/11/2011"
}

###
DELETE https://week03.onrender.com/contacts/645396271394eecc72b83868

### WEEK04
GET https://contacts-lesson04.onrender.com/contacts
###
GET https://contacts-lesson04.onrender.com/contacts/645396271394eecc72b83869
###
POST https://contacts-lesson04.onrender.com/contacts
content-type: application/json

{
	"firstName": "Erwin",
	"lastName": "Smith",
	"email": "erwinsmith@email.com",
	"favoriteColor": "gold",
	"birthday": "02/23/1988"
}
###
PUT https://contacts-lesson04.onrender.com/contacts/645396271394eecc72b83869
content-type: application/json

{
    "favoriteColor": "gray",
    "birthday": "11/11/2011"
}
###
DELETE https://contacts-lesson04.onrender.com/contacts/645396271394eecc72b83869


